apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydining
spec:
  selector:
    matchLabels:
      app: mydining
  replicas: 3  # Adjust the number of replicas as needed
  template:
    metadata:
      labels:
        app: mydining
    spec:
      containers:
      - name: mydining
        image: azizuchiha/speproject:v1
        ports:
        - containerPort: 3000  # Adjust the port if your React app runs on a different port
---
apiVersion: v1
kind: Service
metadata:
  name: mydining
spec:
  type: NodePort
  selector:
    app: mydining
  ports:
  - name: http
    port: 80  # Expose on port 80 if it's a web application
    targetPort: 3000  # Adjust if your React app runs on a different port
    nodePort: 30500
